### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by Geen-19** [devmirza-bot/frameworks-benchmark#2]
Project Seems really cool, a good UI improvement would help the project reach! 
Hence give me some design ideas and I will try to implement that here

**Comment by Zaid-maker** [comment]
> Project Seems really cool, a good UI improvement would help the project reach! Hence give me some design ideas and I will try to implement that here

Thanks for your time for opening a issue.
I made very very basic UI to just fetc data and show them. If u want to improve the UI you can add a dark/light mode, compatible with mobile devices, Navbar and Footer. ♥

**Comment by Geen-19** [comment]
bro, Check out my PR.

**Comment by Zaid-maker** [comment]
> bro, Check out my PR.

I need some time to review it, ♥
